import db from './db.mjs';
import * as MatchDAO from './dao/matchDAO.mjs';
import * as SituationDAO from './dao/situationDAO.mjs';
import { Match, Situation } from './models.mjs';
import * as UserDAO from './dao/userDAO.mjs';

async function main() {
  await MatchDAO.clearMatches();
  await MatchDAO.clearSituationsInMatch();
  await SituationDAO.clearSituations();
  
  /*
  const sit1 = new Situation(0, "INDICE 1", 1, "img/sit1.png");
  await SituationDAO.addSituation(sit1);
  const sit2 = new Situation(1, "INDICE 5", 5, "img/sit2.png");
  await SituationDAO.addSituation(sit2);
  const sit3 = new Situation(2, "INDICE 10", 10, "img/sit3.png");
  await SituationDAO.addSituation(sit3);
  const sit4 = new Situation(3, "INDICE 15", 15, "img/sit4.png");
  await SituationDAO.addSituation(sit4);
  const sit5 = new Situation(4, "INDICE 20", 20, "img/sit5.png");
  await SituationDAO.addSituation(sit5);
  const sit6 = new Situation(5, "INDICE 25", 25, "img/sit6.png");
  await SituationDAO.addSituation(sit6);
  const sit7 = new Situation(6, "INDICE 30", 30, "img/sit7.png");
  await SituationDAO.addSituation(sit7);
  const sit8 = new Situation(7, "INDICE 35", 35, "img/sit8.png");
  await SituationDAO.addSituation(sit8);
  const sit9 = new Situation(8, "INDICE 40", 40, "img/sit9.png");
  await SituationDAO.addSituation(sit9);
  const sit10 = new Situation(9, "INDICE 45", 45, "img/sit10.png");
  await SituationDAO.addSituation(sit10);
  const sit11 = new Situation(10, "INDICE 50", 50, "img/sit11.png");
  await SituationDAO.addSituation(sit11);
  */
  
  const sit1 = new Situation(0, "Dimentichi il caricabatterie del telefono in hotel", 2.5, "/img/caricatore.jpg");
  await SituationDAO.addSituation(sit1);
  const sit2 = new Situation(1, "Ti si rompe la cerniera della valigia appena arrivato", 5.0, "/img/cerniera.jpg");
  await SituationDAO.addSituation(sit2);
  const sit3 = new Situation(2, "Il wifi dell'hotel è lentissimo", 7.5, "/img/wifi.jpg");
  await SituationDAO.addSituation(sit3);
  const sit4 = new Situation(3, "Ti si bagna tutto il bagaglio per la pioggia", 8.0, "/img/pioggia.jpg");
  await SituationDAO.addSituation(sit4);
  const sit5 = new Situation(4, "Ti perdi per 10 minuti in una città nuova", 10.0, "/img/perso.jpg");
  await SituationDAO.addSituation(sit5);
  const sit6 = new Situation(5, "Il tuo volo ha 30 minuti di ritardo", 12.5, "/img/ritardo_volo.jpg");
  await SituationDAO.addSituation(sit6);
  const sit7 = new Situation(6, "Ordini un piatto che non ti piace per niente", 15.0, "/img/brutto_piatto.jpg");
  await SituationDAO.addSituation(sit7);
  const sit8 = new Situation(7, "Ti si scarica il telefono proprio quando devi usare Google Maps", 17.5, "/img/scarico.jpg");
  await SituationDAO.addSituation(sit8);
  const sit9 = new Situation(8, "Non ti prende il telefono sull'isola per mezz'ora da solo", 18.0, "/img/segnale_basso.jpg");
  await SituationDAO.addSituation(sit9);
  const sit10 = new Situation(9, "Perdi un giorno di vacanza per il jet lag", 20.0, "/img/jet_lag.jpg");
  await SituationDAO.addSituation(sit10);
  const sit11 = new Situation(10, "Il tuo bagaglio a mano è troppo grande e devi pagare un extra", 22.5, "/img/bagaglio_grande.jpg");
  await SituationDAO.addSituation(sit11);
  const sit12 = new Situation(11, "Ti ustioni gravemente il primo giorno di mare", 25.0, "/img/scottatura.jpg");
  await SituationDAO.addSituation(sit12);
  const sit13 = new Situation(12, "Prenoti l'hotel sbagliato in una città diversa", 27.5, "/img/hotel_sbagliato.jpg");
  await SituationDAO.addSituation(sit13);
  const sit14 = new Situation(13, "Ti viene negato l'imbarco per overbooking (troppi biglietti venduti)", 28.0, "/img/overbooking.jpg");
  await SituationDAO.addSituation(sit14);
  const sit15 = new Situation(14, "Scopri che la spiaggia dei tuoi sogni è chiusa per inquinamento", 30.0, "/img/spiaggia.jpg");
  await SituationDAO.addSituation(sit15);
  const sit16 = new Situation(15, "Il tuo volo viene cancellato senza preavviso", 32.5, "/img/volo_cancellato.jpg");
  await SituationDAO.addSituation(sit16);
  const sit17 = new Situation(16, "Ti ammali gravemente il secondo giorno di vacanza", 35.0, "/img/febbre.jpg");
  await SituationDAO.addSituation(sit17);
  const sit18 = new Situation(17, "Perdi tutti i documenti in aeroporto", 37.5, "/img/documenti.jpg");
  await SituationDAO.addSituation(sit18);
  const sit19 = new Situation(18, "Ti chiudono fuori dall'hotel senza chiavi", 38.0, "/img/hotel_chiuso.jpg");
  await SituationDAO.addSituation(sit19);
  const sit20 = new Situation(19, "L'hotel che hai prenotato non esiste più", 40.0, "/img/hotel_scompare.jpg");
  await SituationDAO.addSituation(sit20);
  const sit21 = new Situation(20, "Ti perdono le valigie per una settimana", 42.5, "/img/valigia_persa.jpg");
  await SituationDAO.addSituation(sit21);
  const sit22 = new Situation(21, "Rimani bloccato in ascensore in un hotel straniero", 45.0, "/img/ascensore.jpg");
  await SituationDAO.addSituation(sit22);
  const sit23 = new Situation(22, "Ti intossichi con il cibo locale e finisci in ospedale", 47.5, "/img/intossicato.jpg");
  await SituationDAO.addSituation(sit23);
  const sit24 = new Situation(23, "Ti rubano il portafoglio in metro", 48.0, "/img/portafoglio.jpg");
  await SituationDAO.addSituation(sit24);
  const sit25 = new Situation(24, "Scopri che il tuo passaporto è scaduto all'aeroporto", 50.0, "/img/passaporto.jpg");
  await SituationDAO.addSituation(sit25);
  const sit26 = new Situation(25, "Ti derubano mentre dormi in treno", 52.5, "/img/dormo_treno.jpg");
  await SituationDAO.addSituation(sit26);
  const sit27 = new Situation(26, "Il tuo volo di ritorno viene cancellato per uno sciopero", 55.0, "/img/sciopero.jpg");
  await SituationDAO.addSituation(sit27);
  const sit28 = new Situation(27, "Ti arrestano per un malinteso alla dogana", 57.5, "/img/dogana.jpg");
  await SituationDAO.addSituation(sit28);
  const sit29 = new Situation(28, "Ti fratturi il polso cadendo dalle scale dell'hotel", 58.0, "/img/scale.jpg");
  await SituationDAO.addSituation(sit29);
  const sit30 = new Situation(29, "Ti rapiscono per 48 ore in un paese del terzo mondo", 60.0, "/img/africa.jpg");
  await SituationDAO.addSituation(sit30);
  const sit31 = new Situation(30, "Ti si rompe una gamba sciando il primo giorno di vacanza", 62.5, "/img/sciare.jpg");
  await SituationDAO.addSituation(sit31);
  const sit32 = new Situation(31, "L'albergo prende fuoco nel cuore della notte", 65.0, "/img/fuoco.jpg");
  await SituationDAO.addSituation(sit32);
  const sit33 = new Situation(32, "Ti rapinano tutto in una favela di Rio", 67.5, "/img/favela.jpg");
  await SituationDAO.addSituation(sit33);
  const sit34 = new Situation(33, "Rimani senza soldi in un paese dove non accettano carte", 68.0, "/img/carta.jpg");
  await SituationDAO.addSituation(sit34);
  const sit35 = new Situation(34, "Rimani bloccato su un'isola per una tempesta tropicale", 70.0, "/img/isola.jpg");
  await SituationDAO.addSituation(sit35);
  const sit36 = new Situation(35, "Rimani bloccato in un paese per una guerra civile", 72.5, "/img/guerra.jpg");
  await SituationDAO.addSituation(sit36);
  const sit37 = new Situation(36, "Perdi tutti i soldi per una truffa ai bancomat", 75.0, "/img/truffa.jpg");
  await SituationDAO.addSituation(sit37);
  const sit38 = new Situation(37, "Ti viene diagnosticata una malattia tropicale grave", 77.5, "/img/malattia.jpg");
  await SituationDAO.addSituation(sit38);
  const sit39 = new Situation(38, "Uscendo da un ristorante di tacos finisci in una scazzottata col cartello messicano", 78.0, "/img/cartello.jpg");
  await SituationDAO.addSituation(sit39);
  const sit40 = new Situation(39, "Il vulcano dell'isola dove sei in vacanza erutta", 80.0, "/img/vulcano.jpg");
  await SituationDAO.addSituation(sit40);
  const sit41 = new Situation(40, "Ti perdi nella giungla amazzonica per tre giorni", 82.5, "/img/giungla.jpg");
  await SituationDAO.addSituation(sit41);
  const sit42 = new Situation(41, "Rimani coinvolto in un attentato terroristico", 85.0, "/img/attentato.jpg");
  await SituationDAO.addSituation(sit42);
  const sit43 = new Situation(42, "L'aereo su cui viaggi fa un atterraggio di emergenza in mezzo al deserto", 87.5, "/img/deserto.jpg");
  await SituationDAO.addSituation(sit43);
  const sit44 = new Situation(43, "Rimani coinvolto in un colpo di stato mentre sei in vacanza", 88.0, "/img/colpo_di_stato.jpg");
  await SituationDAO.addSituation(sit44);
  const sit45 = new Situation(44, "Ti attacca uno squalo mentre fai immersione", 90.0, "/img/squalo.jpg");
  await SituationDAO.addSituation(sit45);
  const sit46 = new Situation(45, "Rimani intrappolato in una valanga in montagna", 92.5, "/img/valanga.jpg");
  await SituationDAO.addSituation(sit46);
  const sit47 = new Situation(46, "La nave da crociera su cui viaggi affonda", 95.0, "/img/affonda.jpg");
  await SituationDAO.addSituation(sit47);
  const sit48 = new Situation(47, "L'aereo su cui viaggi precipita su un'isola deserta, ma tu sopravvivi ", 97.5, "/img/island.jpg");
  await SituationDAO.addSituation(sit48);
  const sit49 = new Situation(48, "Ti colpisce un fulmine mentre sei in escursione in montagna paralizzandoti", 98.0, "/img/fulmine.jpg");
  await SituationDAO.addSituation(sit49);
  const sit50 = new Situation(49, "Vieni rapito dai pirati durante una gita in barca", 100.0, "/img/pirati.jpg");
  await SituationDAO.addSituation(sit50);

  await UserDAO.clearUsers();
  // password: ciao25
  await UserDAO.addUser("Sebulba", "sebulba@gmail.com", "29820ff3d0dbdbeddaa656a90725a7fb8df0f4579954a4cb25d3565ca45cdc4e", "a33a51ce8fb17672", "/pp/sebulba.jpg");
  // password: stustu
  await UserDAO.addUser("Luigi", "luigi@gmail.com", "7d3e0485d1517800ac701a1c02e837d3834ba01ed343a37433f97466f4e596a9", "d7acb7d6a5ff1c2f", "/pp/ungaretti.jpg");
  
  db.close();
}

main();