import db from './db.mjs';
import * as MatchDAO from './dao/matchDAO.mjs';
import * as SituationDAO from './dao/situationDAO.mjs';
import { Match, Situation } from './models.mjs';
import * as UserDAO from './dao/userDAO.mjs';

async function main() {
  /*
  await SituationDAO.clearSituations();
  const sit1 = new Situation(0, "Dimentichi il caricabatterie del telefono in hotel", 2.5, "img/sit1.png");
  await SituationDAO.addSituation(sit1);
  const sit2 = new Situation(1, "Ti si rompe la cerniera della valigia appena arrivato", 5.0, "img/sit2.png");
  await SituationDAO.addSituation(sit2);
  const sit3 = new Situation(2, "Il wifi dell'hotel è lentissimo", 7.5, "img/sit3.png");
  await SituationDAO.addSituation(sit3);
  const sit4 = new Situation(3, "Ti si bagna tutto il bagaglio per la pioggia", 8.0, "img/sit4.png");
  await SituationDAO.addSituation(sit4);
  const sit5 = new Situation(4, "Ti perdi per 10 minuti in una città nuova", 10.0, "img/sit5.png");
  await SituationDAO.addSituation(sit5);
  const sit6 = new Situation(5, "Il tuo volo ha 30 minuti di ritardo", 12.5, "img/sit6.png");
  await SituationDAO.addSituation(sit6);
  const sit7 = new Situation(6, "Ordini un piatto che non ti piace per niente", 15.0, "img/sit7.png");
  await SituationDAO.addSituation(sit7);
  const sit8 = new Situation(7, "Ti si scarica il telefono proprio quando devi usare Google Maps", 17.5, "img/sit8.png");
  await SituationDAO.addSituation(sit8);
  const sit9 = new Situation(8, "Perdi la connessione per il volo di coincidenza", 18.0, "img/sit9.png");
  await SituationDAO.addSituation(sit9);
  const sit10 = new Situation(9, "Perdi un giorno di vacanza per il jet lag", 20.0, "img/sit10.png");
  await SituationDAO.addSituation(sit10);
  const sit11 = new Situation(10, "Il tuo bagaglio a mano è troppo grande e devi pagare un extra", 22.5, "img/sit11.png");
  await SituationDAO.addSituation(sit11);
  const sit12 = new Situation(11, "Ti ustioni gravemente il primo giorno di mare", 25.0, "img/sit12.png");
  await SituationDAO.addSituation(sit12);
  const sit13 = new Situation(12, "Prenoti l'hotel sbagliato in una città diversa", 27.5, "img/sit13.png");
  await SituationDAO.addSituation(sit13);
  const sit14 = new Situation(13, "Ti viene negato l'imbarco per overbooking", 28.0, "img/sit14.png");
  await SituationDAO.addSituation(sit14);
  const sit15 = new Situation(14, "Scopri che la spiaggia dei tuoi sogni è chiusa per inquinamento", 30.0, "img/sit15.png");
  await SituationDAO.addSituation(sit15);
  const sit16 = new Situation(15, "Il tuo volo viene cancellato senza preavviso", 32.5, "img/sit16.png");
  await SituationDAO.addSituation(sit16);
  const sit17 = new Situation(16, "Ti ammali gravemente il secondo giorno di vacanza", 35.0, "img/sit17.png");
  await SituationDAO.addSituation(sit17);
  const sit18 = new Situation(17, "Perdi tutti i documenti in aeroporto", 37.5, "img/sit18.png");
  await SituationDAO.addSituation(sit18);
  const sit19 = new Situation(18, "Ti chiudono fuori dall'hotel senza chiavi", 38.0, "img/sit19.png");
  await SituationDAO.addSituation(sit19);
  const sit20 = new Situation(19, "L'hotel che hai prenotato non esiste più", 40.0, "img/sit20.png");
  await SituationDAO.addSituation(sit20);
  const sit21 = new Situation(20, "Ti perdono le valigie per una settimana", 42.5, "img/sit21.png");
  await SituationDAO.addSituation(sit21);
  const sit22 = new Situation(21, "Rimani bloccato in ascensore in un hotel straniero", 45.0, "img/sit22.png");
  await SituationDAO.addSituation(sit22);
  const sit23 = new Situation(22, "Ti intossichi con il cibo locale e finisci in ospedale", 47.5, "img/sit23.png");
  await SituationDAO.addSituation(sit23);
  const sit24 = new Situation(23, "Ti rubano il portafoglio in metro", 48.0, "img/sit24.png");
  await SituationDAO.addSituation(sit24);
  const sit25 = new Situation(24, "Scopri che il tuo passaporto è scaduto all'aeroporto", 50.0, "img/sit25.png");
  await SituationDAO.addSituation(sit25);
  const sit26 = new Situation(25, "Ti derubano mentre dormi in treno", 52.5, "img/sit26.png");
  await SituationDAO.addSituation(sit26);
  const sit27 = new Situation(26, "Il tuo volo di ritorno viene cancellato per uno sciopero", 55.0, "img/sit27.png");
  await SituationDAO.addSituation(sit27);
  const sit28 = new Situation(27, "Ti arrestano per un malinteso alla dogana", 57.5, "img/sit28.png");
  await SituationDAO.addSituation(sit28);
  const sit29 = new Situation(28, "Ti fratturi il polso cadendo dalle scale dell'hotel", 58.0, "img/sit29.png");
  await SituationDAO.addSituation(sit29);
  const sit30 = new Situation(29, "Ti sequestrano per 48 ore in un paese del terzo mondo", 60.0, "img/sit30.png");
  await SituationDAO.addSituation(sit30);
  const sit31 = new Situation(30, "Ti si rompe una gamba sciando il primo giorno di vacanza", 62.5, "img/sit31.png");
  await SituationDAO.addSituation(sit31);
  const sit32 = new Situation(31, "L'albergo prende fuoco nel cuore della notte", 65.0, "img/sit32.png");
  await SituationDAO.addSituation(sit32);
  const sit33 = new Situation(32, "Ti rapinano tutto in una favela di Rio", 67.5, "img/sit33.png");
  await SituationDAO.addSituation(sit33);
  const sit34 = new Situation(33, "Rimani senza soldi in un paese dove non accettano carte", 68.0, "img/sit34.png");
  await SituationDAO.addSituation(sit34);
  const sit35 = new Situation(34, "Rimani bloccato su un'isola per una tempesta tropicale", 70.0, "img/sit35.png");
  await SituationDAO.addSituation(sit35);
  const sit36 = new Situation(35, "Rimani bloccato in un paese per una guerra civile", 72.5, "img/sit36.png");
  await SituationDAO.addSituation(sit36);
  const sit37 = new Situation(36, "Perdi tutti i soldi per una truffa ai bancomat", 75.0, "img/sit37.png");
  await SituationDAO.addSituation(sit37);
  const sit38 = new Situation(37, "Ti viene diagnosticata una malattia tropicale grave", 77.5, "img/sit38.png");
  await SituationDAO.addSituation(sit38);
  const sit39 = new Situation(38, "Ti espellono dal paese per aver violato involontariamente una legge locale", 78.0, "img/sit39.png");
  await SituationDAO.addSituation(sit39);
  const sit40 = new Situation(39, "Il vulcano dell'isola dove sei in vacanza erutta", 80.0, "img/sit40.png");
  await SituationDAO.addSituation(sit40);
  const sit41 = new Situation(40, "Ti perdi nella giungla amazzonica per tre giorni", 82.5, "img/sit41.png");
  await SituationDAO.addSituation(sit41);
  const sit42 = new Situation(41, "Rimani coinvolto in un attentato terroristico", 85.0, "img/sit42.png");
  await SituationDAO.addSituation(sit42);
  const sit43 = new Situation(42, "L'aereo su cui viaggi fa un atterraggio di emergenza in mezzo al deserto", 87.5, "img/sit43.png");
  await SituationDAO.addSituation(sit43);
  const sit44 = new Situation(43, "Rimani coinvolto in un colpo di stato mentre sei in vacanza", 88.0, "img/sit44.png");
  await SituationDAO.addSituation(sit44);
  const sit45 = new Situation(44, "Ti attacca uno squalo mentre fai snorkeling", 90.0, "img/sit45.png");
  await SituationDAO.addSituation(sit45);
  const sit46 = new Situation(45, "Rimani intrappolato in una valanga sulle Alpi", 92.5, "img/sit46.png");
  await SituationDAO.addSituation(sit46);
  const sit47 = new Situation(46, "La nave da crociera su cui viaggi affonda", 95.0, "img/sit47.png");
  await SituationDAO.addSituation(sit47);
  const sit48 = new Situation(47, "L'aereo su cui viaggi precipita ma sopravvivi su un'isola deserta", 97.5, "img/sit48.png");
  await SituationDAO.addSituation(sit48);
  const sit49 = new Situation(48, "Ti colpisce un fulmine mentre sei in escursione in montagna", 98.0, "img/sit49.png");
  await SituationDAO.addSituation(sit49);
  const sit50 = new Situation(49, "Vieni rapito da pirati somali nell'Oceano Indiano", 100.0, "img/sit50.png");
  await SituationDAO.addSituation(sit50);
  */

  // password: ciaociao
  await UserDAO.addUser("Luigi", "luigi@gmail.com", "0b4d39f2c97512c307f2521da87645a805931ea9071e98752b23a9c8141d1757d0844d4fe230acee5373c55ebacd3fa9fd73b071e658132faeaf7a49e0d3028b", "894e4736cbbaf01a");
  // password: stustu
  await UserDAO.addUser("Stu", "stu@gmail.com", "270a06d3af1d623f3282130cbad4e5d06beedd9ea79136834e6780687ed95d61458e6d750283759e9870e77961b89ccb4c623dc22a2a05eba582e4c11db44673", "62586d92d9481e3d");

  db.close();
}

main();